name: Cloudflare Pages

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
    #paths:
      #- '.github/workflows/pages.yml'
      #- 'bases/frontend/**'
      #- 'projects/cloudflare/**'
jobs:
  build:
    name: Build with shadow-cljs
    runs-on: ubuntu-latest
    #permissions:
      #contents: read
      #actions: write
      #id-token: write   # REQUIRED for cache API writes in 2024+
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Clojure tools 1.12.0
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.0.1530
          #github-token: ${{ secrets.GITHUB_TOKEN }}

      # Cache Clojure deps
      - name: Cache Clojure deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.cpcache
            ~/.gitlibs
          key: clj-${{ hashFiles('deps.edn') }}

      # Cache npm dependencies
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('projects/frontend/package-lock.json') }}

      - name: Build the application
        run: |
            cd ./projects/frontend/
            npm install
            npx babel ../../bases/frontend/ui --out-dir ../../bases/frontend/js --extensions ".ts,.tsx,.jsx" --ignore "node_modules"
            npx tailwindcss -i ../../bases/frontend/ui/index.css -o ./resources/public/css/index.css
            npm run release
            ls -l ./resources/public/css/
            cp -R ./resources/public/ out/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: compilation
            path: ./projects/frontend/out/

  deploy:
    name: Deploy the app
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: compilation
      # Deploy to Cloudflare Pages
      - name: Deploy frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.7.0"
          workingDirectory: "./"
          command: pages deploy ./public --project-name pmanagement-frontend