name: Cloudflare Pages

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
    #paths:
      #- '.github/workflows/pages.yml'
      #- 'bases/frontend/**'
      #- 'projects/cloudflare/**'
jobs:
  build:
    name: Build with shadow-cljs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Clojure tools 1.12.0
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.12.0
          cache: false

      - name: Build the application
        run: |
            cd ./projects/frontend/
            npm install
            npx babel ../../bases/frontend/ui --out-dir ./js --extensions ".ts,.tsx,.jsx" --ignore "node_modules"
            npm run release
            cp -R resources/public/ out/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: compilation
            path: ./projects/frontend/out/

  deploy:
    name: Deploy the app
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: compilation
      # Deploy to Cloudflare Pages
      - name: Deploy frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.7.0"
          workingDirectory: "./"
          command: pages deploy ./public --project-name pmanagement-frontend