name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  #push:
    #branches: [main, master]
    #paths:
    #- '.github/workflows/worker.yml'
    #- 'bases/worker/**'
    #- 'projects/cloudflare/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: projects/cloudflare/package-lock.json

      - name: Install Clojure tools 1.12.0
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.0.1530

      - name: Install dependencies
        run: cd projects/cloudflare && npm ci

      - name: Build application
        run: |
          cd projects/cloudflare 
          npm run release

      - name: Inject DATABASE_ID into wrangler.toml
        run: |
          projects/cloudflare
          sed -i "s|database_id = \".*\"|database_id = \"${{ secrets.DATABASE_ID }}\"|" wrangler.toml

      - name: Run database migrations
        run: |
          projects/cloudflare  
          npx wrangler d1 migrations apply landlord-db --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Workers
        run: |
          cd projects/cloudflare  
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}